 "use client";
import {useState} from "react";import {supabaseBrowser} from "@/lib/supabase-browser";
export function UploadForm({categories,canPaid}:{categories:any[],canPaid:boolean}){const [loading,setLoading]=useState(false);const [err,setErr]=useState("");
async function submit(e:any){e.preventDefault();setLoading(true);setErr("");const f=new FormData(e.currentTarget);const s=supabaseBrowser();const {data:{user}}=await s.auth.getUser();if(!user){location.href="/login";return}
const type=f.get("mod_type");if(type==="paid"&&!canPaid){setErr("Akun kamu hanya diperbolehkan upload FREE.");setLoading(false);return}
const file=f.get("file") as File;const thumb=f.get("thumbnail") as File;if(!file||file.size>250*1024*1024){setErr("File mod wajib dan maksimal 250MB.");setLoading(false);return}
const ext=file.name.split(".").pop()?.toLowerCase();if(!["zip","rar","7z"].includes(ext||"")){setErr("Format harus ZIP/RAR/7Z.");setLoading(false);return}
const path=`${user.id}/${crypto.randomUUID()}.${ext}`;const up=await s.storage.from("mods").upload(path,file,{upsert:false});if(up.error){setErr(up.error.message);setLoading(false);return}
let thumbnail_url=null;if(thumb?.size){const te=thumb.name.split(".").pop()?.toLowerCase();if(["jpg","jpeg","png","webp"].includes(te||"")){const tp=`${user.id}/${crypto.randomUUID()}.${te}`;const tu=await s.storage.from("thumbnails").upload(tp,thumb,{upsert:false});if(!tu.error)thumbnail_url=s.storage.from("thumbnails").getPublicUrl(tp).data.publicUrl}}
const slug=(String(f.get("title")).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+"-"+Math.random().toString(36).slice(2,7));
const {error}=await s.from("mods").insert({user_id:user.id,category_id:Number(f.get("category_id")),title:f.get("title"),slug,description:f.get("description"),version:f.get("version"),mod_type:type,price:type==="paid"?Number(f.get("price")):0,file_path:path,thumbnail_url,status:"pending"});
if(error){await s.storage.from("mods").remove([path]);setErr(error.message);setLoading(false);return}location.href="/dashboard?uploaded=1"}
return <div className="formCard"><h1>Upload Mod</h1><p className="muted">{canPaid?"Akun admin/owner dapat upload FREE atau PAID.":"Akun kamu hanya dapat upload FREE."}</p>{err&&<div className="alert">{err}</div>}<form onSubmit={submit}><div className="field"><label>Judul</label><input name="title" required maxLength={150}/></div><div className="field"><label>Kategori</label><select name="category_id" required><option value="">Pilih kategori</option>{categories.map(c=><option value={c.id} key={c.id}>{c.game.toUpperCase()} · {c.name}</option>)}</select></div><div className="field"><label>Jenis</label><select name="mod_type" defaultValue="free" onChange={e=>{const p=document.getElementById("priceField");if(p)p.style.display=e.target.value==="paid"?"block":"none"}}><option value="free">FREE</option>{canPaid&&<option value="paid">PAID</option>}</select></div><div id="priceField" className="field" style={{display:"none"}}><label>Harga (Rupiah)</label><input name="price" type="number" min="1000" step="1000" defaultValue="10000"/></div><div className="field"><label>Versi</label><input name="version" defaultValue="1.0.0"/></div><div className="field"><label>Deskripsi</label><textarea name="description" required/></div><div className="field"><label>File Mod</label><input type="file" name="file" accept=".zip,.rar,.7z" required/><div className="hint">Maksimal 250MB.</div></div><div className="field"><label>Thumbnail</label><input type="file" name="thumbnail" accept=".jpg,.jpeg,.png,.webp"/></div><button className="btn primary" disabled={loading}>{loading?"Uploading...":"Submit Mod"}</button></form></div>}
